/*
==========================================================================
Dosya Adı: lang.js
Açıklama: Bu JavaScript dosyası Enes Babekoğlu tarafından oluşturulmuştur.
Oluşturma Tarihi: 25 Nisan 2024
Versiyon: 1.0
Telif Hakkı (c) 2024 Enes Babekoğlu. Tüm hakları saklıdır.
  
İletişim: enesbabekoglu@gmail.com
==========================================================================
*/

/* 
Bu dosyamız dillere ait kelimelerin tutulduğu dosyadır.
*/

var langs = {
    "tr": {
        "tr": "Türkçe",
        "en": "İngilizce",
        "ru": "Rusça",
        "dosyalar_yukleniyor": "Dosyalar Yükleniyor",
        "text_oyna": "Oyna",
        "text_nasil_oynanir": "Nasıl Oynanır?",
        "text_dil_secimi": "Dil Seçimi",
        "text_onay": "Onay",
        "text_red": "Red",
        "text_satin_al": "Satın Al",
        "text_eller_bos": "Eller Boşta",
        "text_elinizde": "Elinizde",
        "hazirlama_alani": "Hazırlama Alanı",
        "teslim_noktasi": "Teslim Noktası",
        "yeni_siparisler": "Yeni Siparişler",
        "market": "Market",
        "et_dolabi": "Et Dolabı", 
        "sebze_dolabi": "Sebze Dolabı", 
        "ekmek_dolabi": "Ekmek Dolabı", 
        "icecek_dolabi": "İçecek Dolabı", 
        "hazirlanmis_urunler_dolabi": "Hazırlanmış Ürünler",
        "kofte": "Köfte",
        "pirzola": "Pirzola",
        "sucuk": "Sucuk",
        "biftek": "Biftek",
        "domates": "Domates",
        "sogan": "Soğan",
        "patates": "Patates",
        "peynir": "Peynir",
        "ekmek": "Ekmek",
        "hamburger_ekmegi": "Hamburger E.",
        "lavas": "Lavaş",
        "ayran": "Ayran",
        "limonata": "Limonata",
        "kola": "Kola",
        "su": "Su",
        "pismis_kofte": "Pişmiş Köfte",
        "pismis_pirzola": "Pişmiş Pirzola",
        "kozlenmis_domates": "Közlenmiş Domates",
        "pismis_sucuk": "Pişmiş Sucuk",
        "pismis_biftek": "Pişmiş Biftek",
        "patates_kizartmasi": "Patates Kız.",
        "salata": "Salata",
        "sogan_halkasi": "Soğan Hal.",
        "peynirli_patates_kizartmasi": "Pey. Pat. Kız.",
        "tost": "Tost",
        "karisik_tabak": "Karışık Tab.",
        "peynirli_salata": "Peyn. Salata",
        "durum": "Dürüm",
        "biftek_tabagi": "Biftek Tab.",
        "sucuk_ekmek": "Sucuk Ekm.",
        "hamburger": "Hamburger",
        "kofte_ekmek": "Köfte Ekm.",
        "pirzola_tabagi": "Pirzola Tab.",
        "text_nasil_oynanir_0": "Babek's Steak House Nedir?",
        "text_nasil_oynanir_1": "Oyunumuz web tarayıcısında oynanabilen bir yemek yapma/restoran yönetme simulasyon oyunudur. Müşterilerden gelen siparişleri kasadan onaylayabilir veya reddedebilirsiniz. Bir siparişi tamamladığınızda sipariş maliyeti + % KAR MARJI oranında kazanç sağlarsınız. Ayrıca ne kadar erken teslim ederseniz o kadar çok yıldız kazanırsınız. Eğer sürenin 2/3'ünden daha erken teslim ederseniz 3, 1/3'ünden daha erken teslim ederseniz 2, daha az sürede teslim ederseniz 1 yıldız kazanırsınız. Yıldızlar şimdilik bir işe yaramıyor ancak yeni özellikler kazanılması için kullanılabilecektir.",
        "text_nasil_oynanir_2": "Karakterimizi Nasıl Hareket Ettiririz?",
        "text_nasil_oynanir_3": "Karakterimizi klavyenin yön tuşlarıyla hareket ettirebilirsiniz.",
        "text_nasil_oynanir_4": "Neden Hiç Sipariş Gelmiyor?",
        "text_nasil_oynanir_5": "Eğer hiç sipariş gelmiyorsa öncelikle sağ üst köşeden dükkanı açtığınızdan emin olunuz. Eğer dükkanı açmanıza rağmen hala sipariş gelmiyorsa algoritma henüz rastgele bir sipariş oluşturamamış demektir. Algoritma her 10 saniyede bir %25 oluşturma ihtimali ile bir sipariş oluşturur.",
        "text_nasil_oynanir_6": "Yeni Siparişleri Nasıl Görebilirim?",
        "text_nasil_oynanir_7": "Yeni gelen siparişlerinizi görebilmek için karakterinizi \"Kasa\" alanına temas ettiriniz. Açılan pencerede yeni gelen siparişleri görüntüleyebilirsiniz ancak acele edin bir siparişi kabul etmek için 1 dakikanız vardır.",
        "text_nasil_oynanir_8": "Siparişi Kabul Ettim Kayboldu?",
        "text_nasil_oynanir_9": "Kabul ettiğiniz siparişler kasanın yanında yer alan \"Teslim Noktası\" alanında görünmektedir. Karakterinizi bu alana temas ettirerek mevcut siparişlerinizi görebilirsiniz. Her bir siparişi teslim etmek için (sipariş onay süresinden kalan süre + 5 dakika) vaktiniz vardır.",
        "text_nasil_oynanir_10": "Siparişteki Ürünleri Nasıl Teslim Ederim?",
        "text_nasil_oynanir_11": "Bir sipariş aldınız ve siparişte istenen bir ürünü hazırladınız bu durumda \"Teslim Noktası\" alanına temas edip açılan pencereden teslim etmek istediğiniz müşterinin teslim edeceğiniz ürün kutucuğuna tıklayabilir ve ürünü teslim edebilirsiniz.",
        "text_nasil_oynanir_12": "Ocak ve Izgara Nasıl Kullanılır?",
        "text_nasil_oynanir_13": "Ocak ve ızgaralarda ürün pişirmek için pişirmek istediğimiz ürünü elimize almalı ve karakterimizi mobilyaya temas ettirip \"P\" tuşuna basmalıyız. Aynı şekilde pişen ürünleri almak içinde aynısını yaparız.",
        "text_nasil_oynanir_14": "Ürün Nasıl Hazırlanır?",
        "text_nasil_oynanir_15": "\"Hazırlama Alanı\" yazan alana karakterimizi temas ettiriyoruz. Açılan pencereden hangi ürün için neler istendiğini görüyoruz ve marketten bu gereken ürünleri satın alıyoruz. Daha sonra tek tek ürünleri elimize alıp tekrar karakterimizi hazırlama alanına temas ettiriyoruz ve elimizdeki ürünü gereken ürünün üzerine basarak ekliyoruz. Tüm ürünleri temin ettiğimizde hazırladığımız ürün elimize gelecektir. Ürünü teslim noktasına götürüp müşteriye teslim ediyoruz.",

    },
    "en": {
        "tr": "Turkish",
        "en": "English",
        "ru": "Russian",
        "dosyalar_yukleniyor" : "Files are loading",
        "text_oyna": "Play",
        "text_nasil_oynanir": "How to Play?",
        "text_dil_secimi": "Select Language",
        "text_onay": "Apply",
        "text_red": "Reject",
        "text_satin_al": "Buy",
        "text_eller_bos": "Hands Free",
        "text_elinizde": "In Your Hands",
        "hazirlama_alani": "Preparation Area",
        "teslim_noktasi": "Delivery Point",
        "yeni_siparisler": "New Orders",
        "market": "Market",
        "et_dolabi": "Meat Fridge",
        "sebze_dolabi": "Vegetable Fridge",
        "ekmek_dolabi": "Bread Cabinet",
        "icecek_dolabi": "Beverage Cooler",
        "hazirlanmis_urunler_dolabi": "Prepared Products",
        "kofte": "Meatballs",
        "pirzola": "Lamb Chops",
        "sucuk": "Sausage",
        "biftek": "Beef Steak",
        "domates": "Tomato",
        "sogan": "Onion",
        "patates": "Potato",
        "peynir": "Cheese",
        "ekmek": "Bread",
        "hamburger_ekmegi": "Hamburger Bun",
        "lavas": "Flatbread",
        "ayran": "Ayran",
        "limonata": "Lemonade",
        "kola": "Cola",
        "su": "Water",
        "pismis_kofte": "Cooked Meatballs",
        "pismis_pirzola": "Cooked Lamb Chops",
        "kozlenmis_domates": "Roasted Tomatoes",
        "pismis_sucuk": "Cooked Sausage",
        "pismis_biftek": "Cooked Beef Steak",
        "patates_kizartmasi": "Potato Wedges",
        "salata": "Salad",
        "sogan_halkasi": "Onion Rings",
        "peynirli_patates_kizartmasi": "Cheesy Potato Wedges",
        "tost": "Toast",
        "karisik_tabak": "Mixed Plate",
        "peynirli_salata": "Cheese Salad",
        "durum": "Wrap",
        "biftek_tabagi": "Beef Steak Plate",
        "sucuk_ekmek": "Sausage Sandwich",
        "hamburger": "Hamburger",
        "kofte_ekmek": "Meatball Sandwich",
        "pirzola_tabagi": "Lamb Chops Plate",
        "text_nasil_oynanir_0": "What is Babek's Steak House?",
        "text_nasil_oynanir_1": "Our game is a cooking/restaurant management simulation game that can be played in a web browser. You can approve or reject orders from customers at the cashier. When you complete an order, you earn a profit equal to the order cost + % PROFIT MARGIN rate. Also, the earlier you deliver, the more stars you earn. If you deliver more than 2/3 of the time, you earn 3 stars; if you deliver more than 1/3 of the time, you earn 2 stars; and if you deliver in less time, you earn 1 star. Stars are currently useless, but they can be used to unlock new features.",
        "text_nasil_oynanir_2": "How Do We Move Our Character?",
        "text_nasil_oynanir_3": "You can move your character with the arrow keys on your keyboard.",
        "text_nasil_oynanir_4": "Why Am I Not Getting Any Orders?",
        "text_nasil_oynanir_5": "If you're not getting any orders, first make sure you've opened the shop from the top right corner. If you've opened the shop and still aren't getting any orders, it means the algorithm hasn't been able to generate a random order yet. The algorithm generates an order with a 25% chance every 10 seconds.",
        "text_nasil_oynanir_6": "How Can I See New Orders?",
        "text_nasil_oynanir_7": "To see your new orders, touch your character to the 'Cashier' area. You can view new incoming orders in the pop-up window, but hurry, you have 1 minute to accept an order.",
        "text_nasil_oynanir_8": "I Accepted an Order but It Disappeared?",
        "text_nasil_oynanir_9": "Accepted orders appear in the 'Delivery Point' area next to the cashier. Touch your character to this area to see your current orders. You have (remaining time from order approval + 5 minutes) to deliver each order.",
        "text_nasil_oynanir_10": "How Do I Deliver Products in an Order?",
        "text_nasil_oynanir_11": "If you have received an order and prepared the requested product, touch the 'Delivery Point' area and click on the product box of the customer you want to deliver to in the pop-up window, then you can deliver the product.",
        "text_nasil_oynanir_12": "How Do I Use the Stove and Grill?",
        "text_nasil_oynanir_13": "To cook products on the stove and grill, we must first pick up the product we want to cook and touch our character to the furniture and press the 'P' key. Similarly, we do the same to pick up cooked products.",
        "text_nasil_oynanir_14": "How Do I Prepare Products?",
        "text_nasil_oynanir_15": "We touch our character to the area labeled 'Preparation Area'. We see what is required for which product in the pop-up window and buy these required products from the market. Then we pick up each product one by one and touch our character to the preparation area again and add the product by pressing on the required product. When we have obtained all the products, the product we have prepared will come to our hand. We take the product to the delivery point and deliver it to the customer."
    },
    "ru": {
        "tr": "Турецкий",
        "en": "Английский",
        "ru": "Русский",
        "dosyalar_yukleniyor" : "Файлы загружаются",
        "text_oyna": "Играть",
        "text_nasil_oynanir": "Как играть?",
        "text_dil_secimi": "Выберите язык",
        "text_onay": "Применить",
        "text_red": "Отклонить",
        "text_satin_al": "Купить",
        "text_eller_bos": "Свободные руки",
        "text_elinizde": "В ваших руках",
        "hazirlama_alani": "Подготовительная зона",
        "teslim_noktasi": "Пункт доставки",
        "yeni_siparisler": "Новые заказы",
        "market": "Магазин",
        "et_dolabi": "Мясной холодильник",
        "sebze_dolabi": "Овощной холодильник",
        "ekmek_dolabi": "Хлебный шкаф",
        "icecek_dolabi": "Напитки холодильник",
        "hazirlanmis_urunler_dolabi": "Готовые продукты",
        "kofte": "Мясные котлеты",
        "pirzola": "Бараньи ребрышки",
        "sucuk": "Колбаса",
        "biftek": "Говяжий стейк",
        "domates": "Помидор",
        "sogan": "Лук",
        "patates": "Картошка",
        "peynir": "Сыр",
        "ekmek": "Хлеб",
        "hamburger_ekmegi": "Булочка для гамбургера",
        "lavas": "Лаваш",
        "ayran": "Айран",
        "limonata": "Лимонад",
        "kola": "Кола",
        "su": "Вода",
        "pismis_kofte": "Приготовленные мясные котлеты",
        "pismis_pirzola": "Приготовленные бараньи ребрышки",
        "kozlenmis_domates": "Запеченные помидоры",
        "pismis_sucuk": "Приготовленная колбаса",
        "pismis_biftek": "Приготовленный говяжий стейк",
        "patates_kizartmasi": "Картофель фри",
        "salata": "Салат",
        "sogan_halkasi": "Кольца лука",
        "peynirli_patates_kizartmasi": "Сырные картофель фри",
        "tost": "Тост",
        "karisik_tabak": "Смешанная тарелка",
        "peynirli_salata": "Сырный салат",
        "durum": "Ролл",
        "biftek_tabagi": "Тарелка с говяжьим стейком",
        "sucuk_ekmek": "Сэндвич с колбасой",
        "hamburger": "Гамбургер",
        "kofte_ekmek": "Сэндвич с мясными котлетами",
        "pirzola_tabagi": "Тарелка с бараньими ребрышками",
        "text_nasil_oynanir_0": "Что такое Babek's Steak House?",
        "text_nasil_oynanir_1": "Наша игра - это симулятор приготовления еды/управления рестораном, который можно играть в веб-браузере. Вы можете подтвердить или отклонить заказы от клиентов на кассе. Когда вы завершаете заказ, вы зарабатываете прибыль в размере стоимости заказа + % ПРИБЫЛЬНЫЙ МАРЖ или. Кроме того, чем раньше вы доставите, тем больше звезд вы заработаете. Если вы доставите более 2/3 времени, вы заработаете 3 звезды; если вы доставите более 1/3 времени, вы заработаете 2 звезды; и если вы доставите за меньшее время, вы заработаете 1 звезду. Звезды в настоящее время бесполезны, но их можно использовать для разблокировки новых функций.",
        "text_nasil_oynanir_2": "Как двигать нашего персонажа?",
        "text_nasil_oynanir_3": "Вы можете двигать своего персонажа с помощью стрелок на клавиатуре.",
        "text_nasil_oynanir_4": "Почему я не получаю заказы?",
        "text_nasil_oynanir_5": "Если вы не получаете заказы, сначала убедитесь, что вы открыли магазин в правом верхнем углу. Если вы открыли магазин и все еще не получаете заказы, это означает, что алгоритм еще не смог сгенерировать случайный заказ. Алгоритм генерирует заказ с вероятностью 25% каждые 10 секунд.",
        "text_nasil_oynanir_6": "Как я могу увидеть новые заказы?",
        "text_nasil_oynanir_7": "Чтобы увидеть ваши новые заказы, коснитесь вашего персонажа в области 'Касса'. Вы можете просматривать новые поступающие заказы во всплывающем окне, но поспешите, у вас есть 1 минута, чтобы принять заказ.",
        "text_nasil_oynanir_8": "Я принял заказ, но он исчез?",
        "text_nasil_oynanir_9": "Принятые заказы отображаются в области 'Точка доставки' рядом с кассой. Коснитесь вашего персонажа в этой области, чтобы увидеть ваши текущие заказы. У вас есть (оставшееся время от подтверждения заказа + 5 минут), чтобы доставить каждый заказ.",
        "text_nasil_oynanir_10": "Как я могу доставить продукты в заказе?",
        "text_nasil_oynanir_11": "Если вы получили заказ и подготовили запрошенный продукт, коснитесь области 'Точка доставки' и щелкните по полю продукта клиента во всплывающем окне, затем вы можете доставить продукт.",
        "text_nasil_oynanir_12": "Как использовать плиту и гриль?",
        "text_nasil_oynanir_13": "Чтобы приготовить продукты на плите и гриле, мы должны сначала взять продукт, который мы хотим приготовить, и коснуться нашего персонажа к мебели и нажать клавишу 'P'. Точно так же мы делаем, чтобы взять приготовленные продукты.",
        "text_nasil_oynanir_14": "Как подготовить продукты?",
        "text_nasil_oynanir_15": "Мы касаемся своего персонажа к области с надписью 'Подготовка'. Во всплывающем окне мы видим, что требуется для какого продукта, и покупаем эти необходимые продукты на рынке. Затем мы поднимаем каждый продукт по очереди и снова касаемся нашего персонажа к области подготовки и добавляем продукт, нажимая на требуемый продукт. Когда мы получаем все продукты, приготовленный продукт придет к нам в руку. Мы берем продукт к точке доставки и доставляем его клиенту."
    }
};

var word = langs["tr"];